<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  const p = new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('用户数据');
    }, 1000)
  })

  // then的返回结果也是一个 promise对象，对象状态由回调函数的执行结果决定
  // 1. 如果回调函数中返回的结果是 非 promise 类型的属性，状态为成功，返回值为对象的成功的值
  // let result = p.then(value  => {
  //   console.log(value);
  //   // return 'i love you';
  //   // 2. 是 promise 对象
  //   return new Promise((resolve, reject) => {
  //     resolve('ok')
  //   })
  //
  // }, reason => {
  //   console.log(reason);
  // })

  // console.log(result); // ok


  // let result = p.then(value  => {
  //   console.log(value);
  //   // return 'i love you';
  //   // 2. 是 promise 对象
  //   return new Promise((resolve, reject) => {
  //     reject('err')
  //   })
  //
  // }, reason => {
  //   console.log(reason);
  // })
  //
  // console.log(result); // err

  let result = p.then(value  => {
    console.log(value);
    // 3. 出错了， 抛出错误
    throw '出错啦';
  }, reason => {
    console.log(reason);
  })

  console.log(result); // 出错啦

  // 因为 then返回的是一个 promise， 所以可以链式调用

  p.then(value => {})
   .then(value => {})
   .then(value => {})
</script>
</body>
</html>
